window.I18N = {
  uk: {
    brand_sub: "Українська кухня в Японії",
    nav_menu: "Меню",
    nav_about: "Про нас",
    nav_reserve: "Бронювання",
    nav_access: "Як дістатися",
    open_maps: "Відкрити в Google Maps",
    kicker: "Домашні смаки • Тепла атмосфера",
    hero_title: "Українська кухня в Японії",
    hero_desc:
      "Борщ, вареники, деруни та десерти — готуємо з любов’ю та пояснюємо страви трьома мовами.",

    hours_label: "Години:",
    hours: "17:00–23:00",
    city_label: "Місто:",
    photo_caption: "Затишна атмосфера, українські смаки та гостинність.",
    days_label: "Дні:",
    days: "Вт–Нд / Пн вихідний",

    menu_title: "Меню",
    menu_sub: "Кілька хітів. Повне меню можна додати окремою сторінкою.",
    about_title: "Про нас",
    about_sub: "Традиційні рецепти, адаптовані з повагою до Японії.",
    about_card1_title: "Домашня традиція",
    about_card1_desc:
      "Класика української кухні з любов’ю та якісних інгредієнтів.",
    about_card2_title: "Комфорт для всіх",
    about_card2_desc: "Є вегетаріанські опції, takeaway та кейтеринг.",

    reserve_title: "Бронювання",
    reserve_sub:
      "Натисни “Забронювати” і ми отримаємо запит (поки що показує демо).",
    reserve_hint: "Потім підключимо: LINE / Google Form / TableCheck.",
    cta_reserve: "Забронювати",
    cta_menu: "Дивитись меню",

    access_title: "Як дістатися",
    access_sub: "Заміни адресу та станцію на реальні.",
    addr_label: "Адреса",
    station_label: "Станція",
    station_text:
      "Найближча станція: 吉野町駅 (Yoshinochō), вихід 3, ~2 хв пішки.",
    copy_btn: "Копіювати",

    modal_title: "Бронювання столика",
    modal_sub: "Це демо-форма. Потім підключимо відправку.",
    f_name: "Ім’я",
    f_phone: "Телефон",
    f_date: "Дата",
    f_people: "Кількість",
    f_note: "Коментар",
    f_note_ph: "Алергії, час, побажання…",
    cancel: "Скасувати",
    send: "Надіслати",
    privacy_hint: "Ми не зберігаємо дані в демо-версії.",

    toast_ok: "✅ OK",
    toast_copied: "📋 Скопійовано",
    toast_copy_failed: "❌ Не вдалося скопіювати",

    footer_note: "Українська кухня в Японії",
    back_to_top: "Наверх ↑",

    menu_categories: [
      { id: "dumplings", label: "Вареники" },
      { id: "mains", label: "Основні" },
      { id: "salads", label: "Салати" },
      { id: "drinks", label: "Напої" },
    ],

    menu_items: [
      {
        title: "Вареники з картоплею та грибами",
        sub: "Вареники з картоплею та грибами, подані зі сметаною",
        price: "¥1000",
        tag: "Вареники",
        cat: "dumplings",
        img: "img/menu/dumplings01.png",
      },
      {
        title: "Вареники з капустою",
        sub: "Вареники з капустою, подані зі сметаною",
        price: "¥1000",
        tag: "Вареники",
        cat: "dumplings",
        img: "img/menu/dumplings02.png",
      },
      {
        title: "Жарені вареники з картоплею та грибами",
        sub: "Жарені вареники з картоплею та грибами, подані зі сметаною",
        price: "¥1000",
        tag: "Вареники",
        cat: "dumplings",
        img: "img/menu/dumplings03.png",
      },
      {
        title: "Жарені вареники з капустою",
        sub: "Жарені вареники з капустою, подані зі сметаною",
        price: "¥1000",
        tag: "Вареники",
        cat: "dumplings",
        img: "img/menu/dumplings03.png",
      },
      {
        title: "Пельмені",
        sub: "Пельмені, подані зі сметаною",
        price: "¥1000",
        tag: "Вареники",
        cat: "dumplings",
        img: "img/menu/dumplings04.png",
      },
      {
        title: "Жарені пельмені",
        sub: "Жарені пельмені, подані зі сметаною",
        price: "¥1000",
        tag: "Вареники",
        cat: "dumplings",
        img: "img/menu/dumplings05.png",
      },
      {
        title: "Узвар",
        sub: "Домашній фруктовий напій",
        price: "¥450",
        tag: "напій",
        cat: "drinks",
        img: "img/menu/uzvar.jpg",
      },
      {
        title: "Шуба",
        sub: "Салат з оселедцем під шубою",
        price: "¥1000",
        tag: "салат",
        cat: "salads",
        img: "img/menu/shuba.png",
      },
      {
        title: "Мімоза",
        sub: "Салат мімоза з консервованою рибою",
        price: "¥1000",
        tag: "салат",
        cat: "salads",
        img: "img/menu/mimosa.png",
      },
      {
        title: "Олів’є",
        sub: "Салат олів’є з ковбасою",
        price: "¥1000",
        tag: "салат",
        cat: "salads",
        img: "img/menu/olivie.png",
      },
      {
        title: "Сирники",
        sub: "Десерт з ягідним соусом",
        price: "¥780",
        tag: "десерт",
        cat: "desserts",
        img: "img/menu/syrnyky.jpg",
      },
      {
        title: "Борщ",
        sub: "Буряковий суп зі сметаною",
        price: "¥980",
        tag: "хіт",
        cat: "mains",
        img: "img/menu/borsch.png",
      },
    ],
  },

  en: {
    brand_sub: "Ukrainian cuisine in Japan",
    nav_menu: "Menu",
    nav_about: "About",
    nav_reserve: "Reservations",
    nav_access: "Access",
    open_maps: "Open in Google Maps",
    kicker: "Home-style flavors • Warm atmosphere",
    hero_title: "Ukrainian Cuisine in Japan",
    hero_desc:
      "Borscht, varenyky, deruny and desserts — we cook with love and explain dishes in 3 languages.",

    hours_label: "Hours:",
    hours: "17:00–23:00",
    city_label: "City:",
    photo_caption: "Cozy vibe, Ukrainian flavors, and hospitality.",
    days_label: "Days:",
    days: "Tue–Sun / Mon closed",

    menu_title: "Menu",
    menu_sub: "A few highlights. Full menu can be added as a separate page.",
    about_title: "About",
    about_sub: "Traditional recipes, respectfully adapted in Japan.",
    about_card1_title: "Home tradition",
    about_card1_desc:
      "Ukrainian classics made with care and quality ingredients.",
    about_card2_title: "Comfort for everyone",
    about_card2_desc: "Vegetarian options, takeaway, and catering available.",

    reserve_title: "Reservations",
    reserve_sub: "Tap “Reserve” — demo form for now.",
    reserve_hint: "Later: LINE / Google Form / TableCheck.",
    cta_reserve: "Reserve",
    cta_menu: "View menu",

    access_title: "Access",
    access_sub: "Replace the address/station with real ones.",
    addr_label: "Address",
    station_label: "Station",
    station_text:
      "Nearest station: Yoshinochō Station (Yokohama Subway Blue Line), Exit 3, ~2 min walk.",
    copy_btn: "Copy",

    modal_title: "Table reservation",
    modal_sub: "Demo form — submission can be connected later.",
    f_name: "Name",
    f_phone: "Phone",
    f_date: "Date",
    f_people: "People",
    f_note: "Note",
    f_note_ph: "Allergies, time, requests...",
    cancel: "Cancel",
    send: "Send",
    privacy_hint: "Demo does not store any data.",

    toast_ok: "✅ OK",
    toast_copied: "📋 Copied",
    toast_copy_failed: "❌ Copy failed",

    footer_note: "Ukrainian cuisine in Japan",
    back_to_top: "Back to top ↑",

    menu_categories: [
      { id: "drinks", label: "Drinks" },
      { id: "sauces", label: "Sauces" },
      { id: "desserts", label: "Desserts" },
      { id: "mains", label: "Mains" },
      { id: "salads", label: "Salads" },
    ],

    menu_items: [
      {
        title: "Uzvar",
        sub: "Traditional homemade dried-fruit drink",
        price: "¥450",
        tag: "drink",
        cat: "drinks",
        img: "img/menu/uzvar.jpg",
      },
      {
        title: "Syrnyky",
        sub: "Sweet cheese pancakes with berry sauce",
        price: "¥780",
        tag: "dessert",
        cat: "desserts",
        img: "img/menu/syrnyky.jpg",
      },
      {
        title: "Borscht",
        sub: "Beet soup served with sour cream",
        price: "¥980",
        tag: "signature",
        cat: "mains",
        img: "img/menu/borscht.jpg",
      },
    ],
  },

  ja: {
    brand_sub: "日本で味わうウクライナ料理",
    nav_menu: "メニュー",
    nav_about: "私たちについて",
    nav_reserve: "予約",
    nav_access: "アクセス",
    open_maps: "Google マップで開く",
    kicker: "家庭の味 • あたたかな雰囲気",
    hero_title: "日本のウクライナ料理",
    hero_desc:
      "ボルシチ、ヴァレーニキ、デルニー、デザートまで。3言語で分かりやすくご案内します。",

    hours_label: "営業時間:",
    hours: "17:00–23:00",
    city_label: "都市:",
    photo_caption: "落ち着いた雰囲気、ウクライナの味とおもてなし。",
    days_label: "営業日:",
    days: "火〜日／月曜定休",

    menu_title: "メニュー",
    menu_sub: "おすすめの一部。フルメニューは別ページに追加できます。",
    about_title: "私たちについて",
    about_sub: "伝統レシピを大切にしつつ、日本で心地よく。",
    about_card1_title: "家庭の伝統",
    about_card1_desc: "素材にこだわったウクライナ定番料理。",
    about_card2_title: "みんなにやさしく",
    about_card2_desc: "ベジ対応・テイクアウト・ケータリングも可能。",

    reserve_title: "予約",
    reserve_sub: "「予約する」— いまはデモフォームです。",
    reserve_hint: "後で：LINE / Googleフォーム / TableCheck。",
    cta_reserve: "予約する",
    cta_menu: "メニューを見る",

    access_title: "アクセス",
    access_sub: "住所・駅情報を実際のものに変更してください。",
    addr_label: "住所",
    station_label: "最寄り駅",
    station_text:
      "最寄り駅：吉野町駅（横浜市営地下鉄ブルーライン）3番出口から徒歩約2分。",
    copy_btn: "コピー",

    modal_title: "席の予約",
    modal_sub: "デモフォーム（送信は後で接続可能）",
    f_name: "お名前",
    f_phone: "電話番号",
    f_date: "日付",
    f_people: "人数",
    f_note: "備考",
    f_note_ph: "アレルギー、時間、要望など…",
    cancel: "キャンセル",
    send: "送信",
    privacy_hint: "デモではデータを保存しません。",

    toast_ok: "✅ OK",
    toast_copied: "📋 コピーしました",
    toast_copy_failed: "❌ コピーできませんでした",

    footer_note: "日本のウクライナ料理店",
    back_to_top: "トップへ ↑",

    menu_categories: [
      { id: "drinks", label: "ドリンク" },
      { id: "sauces", label: "ソース" },
      { id: "desserts", label: "デザート" },
      { id: "mains", label: "メイン" },
      { id: "salads", label: "サラダ" },
    ],

    menu_items: [
      {
        title: "ウズヴァル（Uzvar）",
        sub: "ドライフルーツの自家製ドリンク",
        price: "¥450",
        tag: "ドリンク",
        cat: "drinks",
        img: "img/menu/uzvar.jpg",
      },
      {
        title: "シルニキ（Syrnyky）",
        sub: "ベリーソース添えのチーズパンケーキ",
        price: "¥780",
        tag: "デザート",
        cat: "desserts",
        img: "img/menu/syrnyky.jpg",
      },
      {
        title: "ボルシチ（Borscht）",
        sub: "サワークリーム添えのビーツスープ",
        price: "¥980",
        tag: "おすすめ",
        cat: "mains",
        img: "img/menu/borscht.jpg",
      },
    ],
  },
};
