window.I18N = {
  uk: {
    brand_sub: "Українська кухня в Японії",
    nav_menu: "Меню",
    nav_about: "Про нас",
    nav_reserve: "Бронювання",
    nav_access: "Як дістатися",
    open_maps: "Відкрити в Google Maps",
    kicker: "Домашні смаки • Тепла атмосфера",
    hero_title: "Українська кухня в Японії",
    hero_desc:
      "Страв у нас більше, ніж борщ і вареники — у меню є різні гарячі позиції та закуски, щоб кожен знайшов щось під свій настрій. Це комфортний простір із теплою подачею та увагою до деталей, а також кафе-баром для приємного вечора. Якщо не знаєте, з чого почати, ми із задоволенням підкажемо й допоможемо обрати найкращий варіант. Меню доступне англійською та японською.",
    hours_label: "Години:",
    hours: "17:00–23:00",
    city_label: "Місто:",
    photo_caption: "Затишна атмосфера, українські смаки та гостинність.",
    days_label: "Дні:",
    days: "Вт–Нд / Пн вихідний",
    menu_title: "Меню",
    menu_sub: "Кілька хітів. Повне меню можна додати окремою сторінкою.",
    about_title: "Про нас",
    about_sub: "Традиційні рецепти, адаптовані з повагою до Японії.",
    about_card1_title: "Домашня традиція",
    about_card1_desc:
      "Colibri House — це маленьке сімейне місце української кухні в Йокогамі, куди хочеться зайти «на щось тепле й знайоме». Ми готуємо з турботою, як для своїх: щоб було смачно, ситно й по-домашньому. У нас можна скуштувати українську класику — борщ, вареники та інші традиційні страви, які добре зігрівають і піднімають настрій. Ми завжди раді гостям і стараємося, щоб кожному було комфортно: можна взяти страви з собою (takeaway) або спокійно провести час у затишній атмосфері. Для зручності меню доступне англійською та японською мовами.",
    about_card2_title: "Комфорт для всіх",
    about_card2_desc: "Є вегетаріанські опції, takeaway та кейтеринг.",
    reserve_title: "Бронювання",
    reserve_sub:
      "Бронювання краще робити заздалегідь. Якщо запізнюєтесь — напишіть або зателефонуйте, ми зачекаємо. На запити відповідаємо протягом 48 годин, тож якщо потрібно швидше — найкраще зателефонувати (приймаємо дзвінки з 17:15 до 22:45). Понеділок — вихідний, працюємо з вівторка по неділю.",
    reserve_hint: "Потім підключимо: LINE / Google Form / TableCheck.",
    cta_reserve: "Забронювати",
    cta_menu: "Дивитись меню",
    cta_review: "Написати відгук",
    access_title: "Як дістатися",
    access_sub: "Заміни адресу та станцію на реальні.",
    addr_label: "Адреса",
    station_label: "Станція",
    station_text:
      "Найближча станція: 吉野町駅 (Yoshinochō), вихід 3, ~2 хв пішки.",
    copy_btn: "Копіювати",
    time_placeholder: "Оберіть час",
    time_hint: "Доступно: 17:00–22:00",
    f_time: "Час",
    modal_title: "Бронювання столика",
    modal_sub:
      "Дзвінки приймаємо з 17:15 до 22:45. Запити через форму розглядаємо протягом 48 годин, тож якщо потрібно швидше — краще зателефонувати.",
    f_name: "Ім’я",
    f_phone: "Телефон",
    f_date: "Дата",
    f_people: "Кількість",
    f_note: "Коментар",
    f_note_ph: "Алергії, час, побажання…",
    cancel: "Скасувати",
    send: "Надіслати",
    success_title: "Готово!",
    success_sub:
      "Повідомлення доставлено. Ми зв’яжемося з вами найближчим часом.",
    success_ok: "OK",
    toast_ok: "Запит надіслано! Ми зв’яжемося з вами.",
    toast_failed: "Помилка відправки. Спробуйте ще раз або зателефонуйте.",
    toast_copied: "📋 Скопійовано",
    toast_copy_failed: "❌ Не вдалося скопіювати",
    footer_note: "Українська кухня в Японії",
    back_to_top: "Наверх ↑",
    features_on: "Доступно",
    features_off: "Недоступно",

    about_feat_bar_cafe: "Бар і кафе",
    about_feat_veg: "Вегетаріанські опції",
    about_feat_wc: "Туалет для гостей",
    about_feat_takeaway: "Takeaway / з собою",
    about_feat_reserve: "Бронювання столика",
    about_feat_cash: "Оплата готівкою",
    about_feat_parking_off: "Парковка",
    about_feat_access_off: "Доступність для візків",
    about_feat_card_off: "Оплата картою",

    menu_categories: [
      { id: "dumplings", label: "Вареники" },
      { id: "bliny", label: "Млинці" },
      { id: "mains", label: "Основні" },
      { id: "salads", label: "Салати" },
      { id: "pirozhki", label: "Пирожки" },
      { id: "drinks", label: "Напої" },
    ],

    menu_items: [
      {
        title: "Вареники з картоплею та грибами",
        sub: "Вареники з картоплею та грибами, подані зі сметаною",
        price: "¥1300",
        tag: "Вареники",
        cat: "dumplings",
        img: "img/menu/dumpling01.jpg",
      },
      {
        title: "Вареники з капустою",
        sub: "Вареники з капустою, подані зі сметаною",
        price: "¥1300",
        tag: "Вареники",
        cat: "dumplings",
        img: "img/menu/dumpling01.jpg",
      },
      {
        title: "Жарені вареники з картоплею та грибами",
        sub: "Жарені вареники з картоплею та грибами, подані зі сметаною",
        price: "¥1300",
        tag: "Вареники",
        cat: "dumplings",
        img: "img/menu/dumpling03.jpg",
      },
      {
        title: "Жарені вареники з капустою",
        sub: "Жарені вареники з капустою, подані зі сметаною",
        price: "¥1300",
        tag: "Вареники",
        cat: "dumplings",
        img: "img/menu/dumpling03.jpg",
      },
      {
        title: "Пельмені",
        sub: "Пельмені, подані зі сметаною",
        price: "¥1300",
        tag: "Пельмені",
        cat: "dumplings",
        img: "img/menu/dumpling02.jpg",
      },
      {
        title: "Жарені пельмені",
        sub: "Жарені пельмені, подані зі сметаною",
        price: "¥1300",
        tag: "Пельмені",
        cat: "dumplings",
        img: "img/menu/dumpling04.jpg",
      },
      {
        title: "Млинці з м’ясом",
        sub: "Домашній рецепт млинців з м’ясною начинкою, подані зі сметаною",
        price: "¥800",
        tag: "Млинці",
        cat: "bliny",
        img: "img/menu/bliny01.jpg",
      },
      {
        title: "Млинці з кисломолочним сиром (творогом)",
        sub: "Млинці з кисломолочним сиром (творогом), подані зі сметаною",
        price: "¥800",
        tag: "Млинці",
        cat: "bliny",
        img: "img/menu/bliny02.jpg",
      },
      {
        title: "Борщ",
        sub: "Буряковий суп зі сметаною",
        price: "¥1200",
        tag: "Хіт",
        cat: "mains",
        img: "img/menu/borscht.jpg",
      },
      {
        title: "Смажена курка з медово-гірчичним соусом",
        sub: "Смажена курка з медово-гірчичним соусом",
        price: "¥800",
        tag: "Основне",
        cat: "mains",
        img: "img/menu/chicken.jpg",
      },
      {
        title: "Шуба",
        sub: "Салат з оселедцем, буряком, картоплею та морквою",
        price: "¥1300",
        tag: "Хіт",
        cat: "salads",
        img: "img/menu/salad01.jpg",
      },
      {
        title: "Олів’є",
        sub: "Салат з ковбасою, картоплею, морквою та зеленим горошком",
        price: "¥1200",
        tag: "Салат",
        cat: "salads",
        img: "img/menu/salad02.jpg",
      },
      {
        title: "Мімоза",
        sub: "Салат з рибою, картоплею, морквою та майонезом",
        price: "¥1200",
        tag: "Салат",
        cat: "salads",
        img: "img/menu/salad03.jpg",
      },
      {
        title: "Вінегрет",
        sub: "Салат із варених овочів (буряк, картопля, морква), солоних огірків та цибулі, заправлений олією.",
        price: "¥1200",
        tag: "Салат",
        cat: "salads",
        img: "img/menu/salad04.jpg",
      },
      {
        title: "Буряк з часником і майонезом",
        sub: "Салат з буряком, часником та майонезом",
        price: "¥700",
        tag: "Салат",
        cat: "salads",
        img: "img/menu/salad05.jpg",
      },
      {
        title: "Пиріжок з яйцем та сиром",
        sub: "Пиріжок з яйцем та сиром, запечений до золотистої скоринки",
        price: "¥500",
        tag: "Пиріжки",
        cat: "pirozhki",
        img: "img/menu/pirozhki.jpg",
      },
      {
        title: "Пиріжок з капустою",
        sub: "Пиріжок з капустою, запечений до золотистої скоринки",
        price: "¥500",
        tag: "Пиріжки",
        cat: "pirozhki",
        img: "img/menu/pirozhki.jpg",
      },
    ],
  },

  en: {
    brand_sub: "Ukrainian cuisine in Japan",
    nav_menu: "Menu",
    nav_about: "About",
    nav_reserve: "Reservations",
    nav_access: "Access",
    open_maps: "Open in Google Maps",
    kicker: "Home-style flavors • Warm atmosphere",
    hero_title: "Ukrainian Cuisine in Japan",
    hero_desc:
      "We offer much more than just borscht and vareniki — our menu includes a variety of hot dishes and appetizers, so everyone can find something that fits their mood. Enjoy a comfortable space with warm service and attention to detail, plus a café-bar for a pleasant evening. If you’re not sure where to start, we’ll be happy to recommend favorites and help you choose the best option. The menu is available in English and Japanese",

    hours_label: "Hours:",
    hours: "17:00–23:00",
    city_label: "City:",
    photo_caption: "Cozy vibe, Ukrainian flavors, and hospitality.",
    days_label: "Days:",
    days: "Tue–Sun / Mon closed",

    menu_title: "Menu",
    menu_sub: "A few highlights. Full menu can be added as a separate page.",
    about_title: "About",
    about_sub: "Traditional recipes, respectfully adapted in Japan.",
    about_card1_title: "Home tradition",
    about_card1_desc:
      "Colibri House is a small family-run spot for Ukrainian food in Yokohama — a place to drop in for something warm and familiar. We cook with care, the way we would for our own: hearty, comforting, and truly homemade. Here you can try Ukrainian classics like borscht and vareniki, along with other traditional dishes that warm you up and lift your mood. We’re always happy to welcome guests and make everyone feel comfortable — you can grab your meal to go (takeaway) or enjoy a relaxed time in our cozy atmosphere. For your convenience, the menu is available in English and Japanese.",
    about_card2_title: "Comfort for everyone",
    about_card2_desc: "Vegetarian options, takeaway, and catering available.",

    reserve_title: "Reservations",
    reserve_sub:
      "It’s best to book in advance. If you’re running late, please message or call us — we’ll wait for you. We reply to requests within 48 hours, so if you need a faster response, the best option is to call (calls accepted from 17:15 to 22:45). We’re closed on Mondays and open from Tuesday to Sunday.",
    reserve_hint: "Later: LINE / Google Form / TableCheck.",
    cta_reserve: "Reserve",
    cta_menu: "View menu",
    cta_review: "Write a review",

    access_title: "Access",
    access_sub: "Replace the address/station with real ones.",
    addr_label: "Address",
    station_label: "Station",
    station_text:
      "Nearest station: Yoshinochō Station (Yokohama Subway Blue Line), Exit 3, ~2 min walk.",
    copy_btn: "Copy",
    time_placeholder: "Select a time",
    time_hint: "Available: 17:00–22:00",
    f_time: "Time",
    modal_title: "Table reservation",
    modal_sub:
      "We accept calls from 17:15 to 22:45. Requests submitted via the form are processed within 48 hours, so if you need a faster response, it’s best to call us.",
    f_name: "Name",
    f_phone: "Phone",
    f_date: "Date",
    f_people: "People",
    f_note: "Note",
    f_note_ph: "Allergies, time, requests...",
    cancel: "Cancel",
    send: "Send",
    success_title: "Done!",
    success_sub: "Message delivered. We’ll contact you soon.",
    success_ok: "OK",

    toast_ok: "Request sent! We’ll contact you soon.",
    toast_failed: "Sending failed. Please try again or call us.",
    toast_copied: "📋 Copied",
    toast_copy_failed: "❌ Copy failed",

    footer_note: "Ukrainian cuisine in Japan",
    back_to_top: "Back to top ↑",
    features_on: "Available",
    features_off: "Not available",

    about_feat_bar_cafe: "Bar & café",
    about_feat_veg: "Vegetarian options",
    about_feat_wc: "Restroom",
    about_feat_takeaway: "Takeaway / to-go",
    about_feat_reserve: "Table reservation",
    about_feat_cash: "Cash payment",
    about_feat_parking_off: "Parking",
    about_feat_access_off: "Wheelchair accessibility",
    about_feat_card_off: "Card payment",

    menu_categories: [
      { id: "dumplings", label: "Dumplings" },
      { id: "bliny", label: "Crepes" },
      { id: "mains", label: "Mains" },
      { id: "salads", label: "Salads" },
      { id: "pirozhki", label: "Pirozhki" },
      { id: "drinks", label: "Drinks" },
    ],

    menu_items: [
      {
        title: "Varenyky with Potato and Mushrooms",
        sub: "Varenyky filled with potato and mushrooms, served with sour cream",
        price: "¥1300",
        tag: "Varenyky",
        cat: "dumplings",
        img: "img/menu/dumpling01.jpg",
      },
      {
        title: "Varenyky with Cabbage",
        sub: "Varenyky filled with cabbage, served with sour cream",
        price: "¥1300",
        tag: "Varenyky",
        cat: "dumplings",
        img: "img/menu/dumpling01.jpg",
      },
      {
        title: "Fried Varenyky with Potato and Mushrooms",
        sub: "Fried varenyky filled with potato and mushrooms, served with sour cream",
        price: "¥1300",
        tag: "Varenyky",
        cat: "dumplings",
        img: "img/menu/dumpling03.jpg",
      },
      {
        title: "Fried Varenyky with Cabbage",
        sub: "Fried varenyky filled with cabbage, served with sour cream",
        price: "¥1300",
        tag: "Varenyky",
        cat: "dumplings",
        img: "img/menu/dumpling03.jpg",
      },
      {
        title: "Pelmeni",
        sub: "Pelmeni, served with sour cream",
        price: "¥1300",
        tag: "Pelmeni",
        cat: "dumplings",
        img: "img/menu/dumpling02.jpg",
      },
      {
        title: "Fried Pelmeni",
        sub: "Fried pelmeni, served with sour cream",
        price: "¥1300",
        tag: "Pelmeni",
        cat: "dumplings",
        img: "img/menu/dumpling04.jpg",
      },
      {
        title: "Crepes with Meat",
        sub: "Homestyle Crepes with a meat filling, served with sour cream",
        price: "¥800",
        tag: "Crepes",
        cat: "bliny",
        img: "img/menu/bliny01.jpg",
      },
      {
        title: "Crepes with Cottage Cheese",
        sub: "Crepes filled with cottage cheese, served with sour cream",
        price: "¥800",
        tag: "Crepes",
        cat: "bliny",
        img: "img/menu/bliny02.jpg",
      },
      {
        title: "Borscht",
        sub: "Beet soup served with sour cream",
        price: "¥1200",
        tag: "Hit",
        cat: "mains",
        img: "img/menu/borscht.jpg",
      },
      {
        title: "Fried Chicken with Honey Mustard Sauce",
        sub: "Fried chicken with honey mustard sauce",
        price: "¥800",
        tag: "Main",
        cat: "mains",
        img: "img/menu/chicken.jpg",
      },
      {
        title: "Shuba",
        sub: "Layered salad with herring, beetroot, potato, and carrot",
        price: "¥1300",
        tag: "Hit",
        cat: "salads",
        img: "img/menu/salad01.jpg",
      },
      {
        title: "Olivier",
        sub: "Salad with sausage, potato, carrot, and green peas",
        price: "¥1200",
        tag: "Salad",
        cat: "salads",
        img: "img/menu/salad02.jpg",
      },
      {
        title: "Mimosa",
        sub: "Salad with fish, potato, carrot, and mayonnaise",
        price: "¥1200",
        tag: "Salad",
        cat: "salads",
        img: "img/menu/salad03.jpg",
      },
      {
        title: "Vinaigrette",
        sub: "Salad of boiled vegetables (beetroot, potato, carrot), pickles, and onion, dressed with oil.",
        price: "¥1200",
        tag: "Salad",
        cat: "salads",
        img: "img/menu/salad04.jpg",
      },
      {
        title: "Beetroot with Garlic and Mayonnaise",
        sub: "Salad with beetroot, garlic, and mayonnaise",
        price: "¥700",
        tag: "Salad",
        cat: "salads",
        img: "img/menu/salad05.jpg",
      },
      {
        title: "Pirozhok with Egg and Cheese",
        sub: "Pirozhok with egg and cheese, baked until golden brown",
        price: "¥500",
        tag: "Pirozhki",
        cat: "pirozhki",
        img: "img/menu/pirozhki.jpg",
      },
      {
        title: "Pirozhok with Cabbage",
        sub: "Pirozhok with cabbage, baked until golden brown",
        price: "¥500",
        tag: "Pirozhki",
        cat: "pirozhki",
        img: "img/menu/pirozhki.jpg",
      },
    ],
  },

  ja: {
    brand_sub: "日本で味わうウクライナ料理",
    nav_menu: "メニュー",
    nav_about: "私たちについて",
    nav_reserve: "予約",
    nav_access: "アクセス",
    open_maps: "Google マップで開く",
    kicker: "家庭の味 • あたたかな雰囲気",
    hero_title: "日本のウクライナ料理",
    hero_desc:
      "ボルシチやヴァレーニキだけでなく、さまざまな温かい料理や前菜をご用意しており、その日の気分に合わせてお選びいただけます。落ち着いた空間で、丁寧なサービスと細やかなこだわりをお楽しみください。カフェバーもございますので、ゆっくりとした夜の時間にもぴったりです。何を選べばよいか迷ったら、おすすめをご案内し、最適な一皿選びをお手伝いします。メニューは英語と日本語に対応しています。",

    hours_label: "営業時間:",
    hours: "17:00–23:00",
    city_label: "都市:",
    photo_caption: "落ち着いた雰囲気、ウクライナの味とおもてなし。",
    days_label: "営業日:",
    days: "火〜日／月曜定休",

    menu_title: "メニュー",
    menu_sub: "おすすめの一部。フルメニューは別ページに追加できます。",
    about_title: "私たちについて",
    about_sub: "伝統レシピを大切にしつつ、日本で心地よく。",
    about_card1_title: "家庭の伝統",
    about_card1_desc: "素材にこだわったウクライナ定番料理。",
    about_card2_title: "みんなにやさしく",
    about_card1_desc:
      "Colibri Houseは横浜にある小さな家族経営のウクライナ料理店です。「温かくてどこか懐かしいもの」を食べたくなったときに、ふらっと立ち寄れる場所を目指しています。私たちは自分たちの家族に作るように心を込めて料理し、しっかり満足できる家庭の味を大切にしています。ボルシチやヴァレーニキなどの定番料理をはじめ、体も心も温まる伝統的なウクライナ料理をお楽しみいただけます。テイクアウトも可能で、店内では落ち着いた雰囲気の中でゆっくりお過ごしいただけます。メニューは英語と日本語に対応しています。",

    reserve_title: "予約",
    reserve_sub:
      "ご予約は事前のご連絡がおすすめです。遅れそうな場合は、メッセージまたはお電話でお知らせください。ご予約のご連絡は48時間以内に返信いたしますが、お急ぎの場合はお電話が最も早いです（受付時間：17:15〜22:45）。月曜日は定休日で、火曜日〜日曜日は営業しています。",
    reserve_hint: "後で：LINE / Googleフォーム / TableCheck。",
    cta_reserve: "予約する",
    cta_menu: "メニューを見る",
    cta_review: "口コミを書く",

    access_title: "アクセス",
    access_sub: "住所・駅情報を実際のものに変更してください。",
    addr_label: "住所",
    station_label: "最寄り駅",
    station_text:
      "最寄り駅：吉野町駅（横浜市営地下鉄ブルーライン）3番出口から徒歩約2分。",
    copy_btn: "コピー",
    time_placeholder: "時間を選択",
    time_hint: "利用可能: 17:00–22:00",
    f_time: "時間",
    modal_title: "席の予約",
    modal_sub:
      "お電話の受付時間は 17:15〜22:45 です。フォームからのご予約リクエストは 48時間以内 に対応いたしますので、お急ぎの場合は お電話 ください。",
    f_name: "お名前",
    f_phone: "電話番号",
    f_date: "日付",
    f_people: "人数",
    f_note: "備考",
    f_note_ph: "アレルギー、時間、要望など…",
    cancel: "キャンセル",
    send: "送信",
    success_title: "送信完了",
    success_sub: "メッセージを送信しました。折り返しご連絡いたします。",
    success_ok: "OK",

    toast_ok: "送信しました。折り返しご連絡いたします。",
    toast_failed:
      "送信に失敗しました。もう一度お試しください。お急ぎの場合はお電話ください。",
    toast_copied: "📋 コピーしました",
    toast_copy_failed: "❌ コピーできませんでした",

    footer_note: "日本のウクライナ料理店",
    back_to_top: "トップへ ↑",
    features_on: "ごりよういただけます",
    features_off: "りようふか",
    about_feat_bar_cafe: "ばー あんど かふぇ",
    about_feat_veg: "べじたりあん たいおう",
    about_feat_wc: "おてあらい",
    about_feat_takeaway: "ていくあうと",
    about_feat_reserve: "せきのごよやく",
    about_feat_cash: "げんきんばらい",
    about_feat_parking_off: "ちゅうしゃじょう",
    about_feat_access_off: "くるまいす たいおう",
    about_feat_card_off: "かーどばらい",

    menu_categories: [
      { id: "dumplings", label: "ぎょうざ" },
      { id: "bliny", label: "ブリニ" },
      { id: "mains", label: "メイン" },
      { id: "salads", label: "サラダ" },
      { id: "pirozhki", label: "ピロシキ" },
      { id: "drinks", label: "ドリンク" },
    ],

    menu_items: [
      {
        title: "ヴァレーニキ ジャガイモとマッシュルーム添え",
        sub: "ポテトとマッシュルーム入りのヴァレーニキ。サワークリーム添え",
        price: "¥1300",
        tag: "ヴァレーニキ",
        cat: "dumplings",
        img: "img/menu/dumpling01.jpg",
      },
      {
        title: "ヴァレーニキ キャベツ入り",
        sub: "キャベツ入りのヴァレーニキ。サワークリーム添え",
        price: "¥1300",
        tag: "ヴァレーニキ",
        cat: "dumplings",
        img: "img/menu/dumpling01.jpg",
      },
      {
        title: "ヤキヴァレニキ ポテトとマッシュルーム",
        sub: "ポテトとマッシュルーム入りのヤキヴァレーニキ。サワークリーム添え",
        price: "¥1300",
        tag: "ヴァレーニキ",
        cat: "dumplings",
        img: "img/menu/dumpling03.jpg",
      },
      {
        title: "ヤキヴァレニキ キャベツ入り",
        sub: "キャベツ入りのヤキヴァレーニキ。サワークリーム添え",
        price: "¥1300",
        tag: "ヴァレーニキ",
        cat: "dumplings",
        img: "img/menu/dumpling03.jpg",
      },
      {
        title: "ペルメニ",
        sub: "ペルメニ。サワークリーム添え",
        price: "¥1300",
        tag: "ペルメニ",
        cat: "dumplings",
        img: "img/menu/dumpling02.jpg",
      },
      {
        title: "ヤキペリメニ",
        sub: "ヤキペルメニ。サワークリーム添え",
        price: "¥1300",
        tag: "ペルメニ",
        cat: "dumplings",
        img: "img/menu/dumpling04.jpg",
      },
      {
        title: "ブリニ肉入り",
        sub: "肉入りの手作りブリニ。サワークリーム添え",
        price: "¥800",
        tag: "ブリニ",
        cat: "bliny",
        img: "img/menu/bliny01.jpg",
      },
      {
        title: "ブリニ カッテージチーズ入り",
        sub: "カッテージチーズ入りのブリニ。サワークリーム添え",
        price: "¥800",
        tag: "ブリニ",
        cat: "bliny",
        img: "img/menu/bliny02.jpg",
      },
      {
        title: "ボルシチ",
        sub: "ビーツのスープ。サワークリーム添え",
        price: "¥1200",
        tag: "人気",
        cat: "mains",
        img: "img/menu/borscht.jpg",
      },
      {
        title: "ハニーマスタードソースの フライドチキン",
        sub: "ハニーマスタードソースの フライドチキン",
        price: "¥800",
        tag: "メイン",
        cat: "mains",
        img: "img/menu/chicken.jpg",
      },
      {
        title: "シューバサラダ",
        sub: "ニシン、ビーツ、ポテト、にんじんのミルフィーユサラダ",
        price: "¥1300",
        tag: "人気",
        cat: "salads",
        img: "img/menu/salad01.jpg",
      },
      {
        title: "オリヴィエ",
        sub: "ソーセージ、ポテト、にんじん、グリーンピースのサラダ",
        price: "¥1200",
        tag: "サラダ",
        cat: "salads",
        img: "img/menu/salad02.jpg",
      },
      {
        title: "ミモザサラダ",
        sub: "魚、ポテト、にんじん、マヨネーズのサラダ",
        price: "¥1200",
        tag: "サラダ",
        cat: "salads",
        img: "img/menu/salad03.jpg",
      },
      {
        title: "ビネグレットサラダ",
        sub: "茹で野菜（ビーツ、ポテト、にんじん）、ピクルス、玉ねぎのサラダ。オイルドレッシング",
        price: "¥1200",
        tag: "サラダ",
        cat: "salads",
        img: "img/menu/salad04.jpg",
      },
      {
        title: "サラダ、ニンニク入りビー ツとマヨネーズ",
        sub: "ビーツ、にんにく、マヨネーズのサラダ",
        price: "¥700",
        tag: "サラダ",
        cat: "salads",
        img: "img/menu/salad05.jpg",
      },
      {
        title: "ピロシキ(エッグ&チーズ)",
        sub: "エッグ＆チーズ入りのピロシキ。こんがり焼き上げ",
        price: "¥500",
        tag: "ピロシキ",
        cat: "pirozhki",
        img: "img/menu/pirozhki.jpg",
      },
      {
        title: "ピロシキ(キャベツ)",
        sub: "キャベツ入りのピロシキ。こんがり焼き上げ",
        price: "¥500",
        tag: "ピロシキ",
        cat: "pirozhki",
        img: "img/menu/pirozhki.jpg",
      },
    ],
  },
};
